//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfgApp
    {
        public int Id { get; set; }
        public int Uid { get; set; }
        public string AppName { get; set; }
        public string AppLogo { get; set; }
        public string HuanXin_Key { get; set; }
        public string HuanXin_Id { get; set; }
        public string HuanXin_Secret { get; set; }
        public string Jpush_Key { get; set; }
        public string Jpush_Secret { get; set; }
        public string WeiXin_AppId { get; set; }
        public string WeiXin_MchId { get; set; }
        public string WeiXin_Key { get; set; }
        public string WeiXin_Secret { get; set; }
        public string WeiXin_Ip { get; set; }
        public string Ali_PublicKey { get; set; }
        public string Ali_Private { get; set; }
        public string Ali_AppId { get; set; }
        public string Agora_Key { get; set; }
        public string GaoDeKey { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    }
}
