//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfgAreaInfo
    {
        public int Id { get; set; }
        public string NodeName { get; set; }
        public int ParentId { get; set; }
        public string ParentIdList { get; set; }
        public int OrderID { get; set; }
        public string Remark { get; set; }
        public int State { get; set; }
        public string TreePath { get; set; }
        public int TreeLevel { get; set; }
        public bool Service { get; set; }
    }
}
