//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eqEquipment_Watch
    {
        public int Id { get; set; }
        public string Imei { get; set; }
        public int GPSInterval { get; set; }
        public Nullable<int> SitWarningDuration { get; set; }
        public string HeartRange { get; set; }
        public string SleepRange { get; set; }
        public int HeartRateInterval { get; set; }
        public string IsPosition { get; set; }
        public string DatePosition { get; set; }
        public string LatitudeConv { get; set; }
        public string LongitudeConv { get; set; }
        public string Address { get; set; }
        public byte ConvertType { get; set; }
        public string MobilePhone { get; set; }
        public string SOSPhone { get; set; }
        public bool IsHeartRangeStat { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
