//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eqHealthData
    {
        public int Id { get; set; }
        public int ElderlyId { get; set; }
        public double Weight_Data { get; set; }
        public Nullable<System.DateTime> WeightTest_Time { get; set; }
        public double Temp_Data { get; set; }
        public Nullable<System.DateTime> TempTest_Time { get; set; }
        public double Systolic { get; set; }
        public double Diastolic { get; set; }
        public double Pulse { get; set; }
        public Nullable<System.DateTime> BloodPressureTest_Time { get; set; }
        public double Moisture { get; set; }
        public double Fat_Grade { get; set; }
        public double Muscle { get; set; }
        public double Fat_Per { get; set; }
        public Nullable<System.DateTime> BodyFatTest_Time { get; set; }
        public double Fpg { get; set; }
        public Nullable<System.DateTime> FpgTest_Time { get; set; }
        public int HeartRate { get; set; }
        public Nullable<System.DateTime> HeartRateTest_Time { get; set; }
        public int TrunOver { get; set; }
        public int Time { get; set; }
        public Nullable<System.DateTime> SleepTest_Time { get; set; }
        public int Steps { get; set; }
        public Nullable<System.DateTime> StepsTest_Time { get; set; }
        public int SitTime { get; set; }
        public Nullable<System.DateTime> SitTime_Time { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    }
}
