//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eqLocation
    {
        public int Id { get; set; }
        public string Imei { get; set; }
        public int ElderlyId { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string IsPosition { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Speed { get; set; }
        public string Direction { get; set; }
        public string Altitude { get; set; }
        public string BaseStation { get; set; }
        public string WiFi { get; set; }
        public string Elec { get; set; }
        public string Gsensor { get; set; }
        public string Address { get; set; }
        public string LatitudeConv { get; set; }
        public string LongitudeConv { get; set; }
        public Nullable<byte> FenceWarn { get; set; }
        public Nullable<int> FenceId { get; set; }
        public Nullable<System.DateTime> StayDate { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
