//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoArticleTags
    {
        public int Id { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
