//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cfgApp> cfgApp { get; set; }
        public virtual DbSet<cfgAreaInfo> cfgAreaInfo { get; set; }
        public virtual DbSet<cfgCategory> cfgCategory { get; set; }
        public virtual DbSet<cfgSite> cfgSite { get; set; }
        public virtual DbSet<eqBeiTai_BloodPressure> eqBeiTai_BloodPressure { get; set; }
        public virtual DbSet<eqBeiTai_BloodSugar> eqBeiTai_BloodSugar { get; set; }
        public virtual DbSet<eqBeiTai_BodyFat> eqBeiTai_BodyFat { get; set; }
        public virtual DbSet<eqBeiTai_Temp> eqBeiTai_Temp { get; set; }
        public virtual DbSet<eqBeiTai_Weight> eqBeiTai_Weight { get; set; }
        public virtual DbSet<eqEquipment> eqEquipment { get; set; }
        public virtual DbSet<eqEquipment_Mattress> eqEquipment_Mattress { get; set; }
        public virtual DbSet<eqEquipment_Watch> eqEquipment_Watch { get; set; }
        public virtual DbSet<eqFence> eqFence { get; set; }
        public virtual DbSet<eqHealthData> eqHealthData { get; set; }
        public virtual DbSet<eqLocation> eqLocation { get; set; }
        public virtual DbSet<eqMattress_Data> eqMattress_Data { get; set; }
        public virtual DbSet<eqWarning> eqWarning { get; set; }
        public virtual DbSet<eqWatch_Heart> eqWatch_Heart { get; set; }
        public virtual DbSet<eqWatch_OutlineData> eqWatch_OutlineData { get; set; }
        public virtual DbSet<eqWatch_Remind> eqWatch_Remind { get; set; }
        public virtual DbSet<eqWatch_Sit> eqWatch_Sit { get; set; }
        public virtual DbSet<eqWatch_Sleep> eqWatch_Sleep { get; set; }
        public virtual DbSet<eqWatch_Step> eqWatch_Step { get; set; }
        public virtual DbSet<infoAdvert> infoAdvert { get; set; }
        public virtual DbSet<infoAppVersion> infoAppVersion { get; set; }
        public virtual DbSet<infoArticle> infoArticle { get; set; }
        public virtual DbSet<infoArticleTags> infoArticleTags { get; set; }
        public virtual DbSet<infoFile> infoFile { get; set; }
        public virtual DbSet<infoMedicine> infoMedicine { get; set; }
        public virtual DbSet<infoMedicine_AddLog> infoMedicine_AddLog { get; set; }
        public virtual DbSet<infoMedicine_ChangeLog> infoMedicine_ChangeLog { get; set; }
        public virtual DbSet<infoMessage> infoMessage { get; set; }
        public virtual DbSet<infoMessageUser> infoMessageUser { get; set; }
        public virtual DbSet<logUser> logUser { get; set; }
        public virtual DbSet<pmAccount> pmAccount { get; set; }
        public virtual DbSet<pmFeedback> pmFeedback { get; set; }
        public virtual DbSet<pmInfo_Doctor> pmInfo_Doctor { get; set; }
        public virtual DbSet<pmInfo_Elderly> pmInfo_Elderly { get; set; }
        public virtual DbSet<pmInfo_User> pmInfo_User { get; set; }
        public virtual DbSet<pmPersonalService> pmPersonalService { get; set; }
        public virtual DbSet<pmPersonalService_Elderly> pmPersonalService_Elderly { get; set; }
        public virtual DbSet<pmProject> pmProject { get; set; }
        public virtual DbSet<pmRelation> pmRelation { get; set; }
        public virtual DbSet<pmSettlement> pmSettlement { get; set; }
        public virtual DbSet<pmTag> pmTag { get; set; }
        public virtual DbSet<reportCheckUp> reportCheckUp { get; set; }
        public virtual DbSet<reportChronicDisease> reportChronicDisease { get; set; }
        public virtual DbSet<reportDaily> reportDaily { get; set; }
        public virtual DbSet<reportMedicalHistory> reportMedicalHistory { get; set; }
        public virtual DbSet<reportNursing> reportNursing { get; set; }
        public virtual DbSet<servCallLog> servCallLog { get; set; }
        public virtual DbSet<servCard> servCard { get; set; }
        public virtual DbSet<servCard_Elderly> servCard_Elderly { get; set; }
        public virtual DbSet<servCard_ElderlyProject> servCard_ElderlyProject { get; set; }
        public virtual DbSet<servCard_Project> servCard_Project { get; set; }
        public virtual DbSet<servOrder> servOrder { get; set; }
        public virtual DbSet<servOrder_Evaluate> servOrder_Evaluate { get; set; }
        public virtual DbSet<servOrder_Project> servOrder_Project { get; set; }
        public virtual DbSet<servOrder_Waiter> servOrder_Waiter { get; set; }
        public virtual DbSet<servProject> servProject { get; set; }
        public virtual DbSet<servReservation> servReservation { get; set; }
        public virtual DbSet<servVisit> servVisit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SysFunctions> SysFunctions { get; set; }
        public virtual DbSet<SysRoles> SysRoles { get; set; }
        public virtual DbSet<SysUser_Roles> SysUser_Roles { get; set; }
    }
}
