//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmInfo_Doctor
    {
        public int Id { get; set; }
        public int Uid { get; set; }
        public string Contact { get; set; }
        public bool Sex { get; set; }
        public string IDCard { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string HeadImg { get; set; }
        public int Position { get; set; }
        public int Department { get; set; }
        public decimal ReservationMoney { get; set; }
        public string Specialty { get; set; }
        public string Description { get; set; }
        public int Province { get; set; }
        public int City { get; set; }
        public int Area { get; set; }
        public int Street { get; set; }
        public string Address { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    }
}
