//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pmInfo_Elderly
    {
        public int Id { get; set; }
        public int ElderlyId { get; set; }
        public int ElderlyType { get; set; }
        public string ElderlyName { get; set; }
        public string ElderlyNo { get; set; }
        public string IDCard { get; set; }
        public bool Sex { get; set; }
        public double Height { get; set; }
        public string BornYM { get; set; }
        public double Weight { get; set; }
        public string HeadImg { get; set; }
        public byte BloodType { get; set; }
        public int NurseRequires { get; set; }
        public int Province { get; set; }
        public int City { get; set; }
        public int Area { get; set; }
        public int Street { get; set; }
        public int AreaInfo { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string ContactTelephone { get; set; }
        public int Sort { get; set; }
        public string Remark { get; set; }
        public string Groupid { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    }
}
