//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servProject
    {
        public servProject()
        {
            this.pmProject = new HashSet<pmProject>();
            this.servCard_Project = new HashSet<servCard_Project>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> ProjectType { get; set; }
        public int ParentId { get; set; }
        public string ServiceName { get; set; }
        public string Icon { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public byte PriceUnit { get; set; }
        public bool IsSignIn { get; set; }
        public bool IsSelect { get; set; }
        public byte State { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    
        public virtual ICollection<pmProject> pmProject { get; set; }
        public virtual ICollection<servCard_Project> servCard_Project { get; set; }
    }
}
