//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servOrder_Project
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public bool Free { get; set; }
        public int TimeService { get; set; }
        public byte TimeUnit { get; set; }
        public decimal Price { get; set; }
        public Nullable<byte> PriceUnit { get; set; }
        public decimal Paid { get; set; }
        public string Remark { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    }
}
