//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servOrder
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public int ElderlyId { get; set; }
        public int Uid { get; set; }
        public int CustomerId { get; set; }
        public int WaiterId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime DateService { get; set; }
        public decimal Paid { get; set; }
        public decimal PaidTotal { get; set; }
        public bool IsSignIn { get; set; }
        public int Province { get; set; }
        public int City { get; set; }
        public int Area { get; set; }
        public int Street { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
        public string Remark { get; set; }
        public bool IsPaid { get; set; }
        public bool PaidType { get; set; }
        public byte State { get; set; }
        public Nullable<decimal> PaidToWaiter { get; set; }
        public Nullable<System.DateTime> DateSuccess { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    }
}
