//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servOrder_Evaluate
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public int Uid { get; set; }
        public int WaiterId { get; set; }
        public string Evaluate { get; set; }
        public string EvaluateTags { get; set; }
        public Nullable<int> EvaluateScore { get; set; }
        public Nullable<System.DateTime> EvaluateDate { get; set; }
        public string WaiterEvaluate { get; set; }
        public string WaiterEvaluateTags { get; set; }
        public Nullable<int> WaiterEvaluateScore { get; set; }
        public Nullable<System.DateTime> WaiterEvaluateDate { get; set; }
        public int CreateById { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int BelongId { get; set; }
        public string BelongIds { get; set; }
    }
}
